// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/3/2025, 4:55:30 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/user/divar-ad-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/divar-ad-frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/divar-ad-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/divar-ad-frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/divar-ad-frontend/plugins/**/*.{js,ts,mjs}","/home/user/divar-ad-frontend/composables/**/*.{js,ts,mjs}","/home/user/divar-ad-frontend/utils/**/*.{js,ts,mjs}","/home/user/divar-ad-frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/divar-ad-frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/user/divar-ad-frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/user/divar-ad-frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;