// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/3/2025, 10:38:20 PM
const configMerger = require("/home/user/divar-ad-frontend/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/home/user/divar-ad-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/divar-ad-frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/divar-ad-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/divar-ad-frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/divar-ad-frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/user/divar-ad-frontend/plugins/**/*.{js,ts,mjs}","/home/user/divar-ad-frontend/composables/**/*.{js,ts,mjs}","/home/user/divar-ad-frontend/utils/**/*.{js,ts,mjs}","/home/user/divar-ad-frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/user/divar-ad-frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/user/divar-ad-frontend/app.config.{js,ts,mjs}"] }));

module.exports = config
